# Generated by Django 3.0.1 on 2019-12-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=7)),
                ('head_id', models.IntegerField()),
                ('head_table', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilePartitionFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte_array', models.BinaryField()),
                ('next_id', models.IntegerField()),
                ('next_table', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilePartitionOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte_array', models.BinaryField()),
                ('next_id', models.IntegerField()),
                ('next_table', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilePartitionThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte_array', models.BinaryField()),
                ('next_id', models.IntegerField()),
                ('next_table', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FilePartitionTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte_array', models.BinaryField()),
                ('next_id', models.IntegerField()),
                ('next_table', models.IntegerField()),
            ],
        ),
    ]
