# Generated by Django 3.0.1 on 2019-12-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudsecurity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetails',
            name='file_name',
            field=models.CharField(max_length=2000),
        ),
    ]
